accounts/urls.py
from django.urls import path
from django.urls import re_path as url
from .import views

app_name='accounts'

urlpatterns=[
    path('', views.index, name="index"),
    path('sign_up/', views.sign_up, name="sign_up"),
    path('login/', views.user_login, name="user_login"),
    path('logout/', views.user_logout, name="user_logout"),
    path('profile/', views.user_profile, name="user_profile"),
    ]

landing/urls.py
from django.urls import path
from django.urls import re_path as url
from .import views

app_name='landing'

urlpatterns=[
    path('', views.index, name="index"),
    ]

library/urls.py
from django.urls import path
from django.urls import re_path as url
from . import views

app_name = 'library'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'books/$',views.books, name='books'),
    #path('', views.index, name='index'),
    #path('books/', views.books, name='books'),
]

library_mgmt/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('landing.urls')),
    path('library/', include('library.urls')),
    path('accounts/', include('accounts.urls')),
    path('checkout/', include('checkout.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include("django.contrib.auth.urls")),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
  pass

  def __str__(self):
    return self.username

landing/models.py
from django.db import models

# Create your models here.

library/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Book(models.Model):
    name = models.CharField(max_length=250)
    author = models.CharField(max_length=250)
    available = models.BooleanField()

    def __str__(self):
      return self.name

''''
class Checkout(models.Model):
    userid = models.ForeignKey('Member', models.DO_NOTHING, db_column='userid', blank=True, null=True)
    bookid = models.ForeignKey(Book, models.DO_NOTHING, db_column='bookid', blank=True, null=True)

    def __str__(self):
      return self.name


class Member(models.Model):
    name = models.CharField(max_length=100)
    age = models.IntegerField()

    def __str__(self):
      return self.name
'''

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import User

class CustomUserCreationForm(UserCreationForm):

  class Meta:
    model = User
    fields = ("username", "email")

class CustomUserChangeForm(UserChangeForm):

  class Meta:
    model = User
    fields= ("username", "email")

accounts/views.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from .forms import CustomUserCreationForm
from django.shortcuts import redirect
from django.contrib import messages
from checkout.models import Checkout
from accounts.models import User
from library.models import Book
from library.serializers import BookSerializer
# Create your views here.

def index(request):
  if  not request.user.is_authenticated: 
    return redirect("login/")
  return render(request, 'accounts/index.html')

def user_profile(request):
  if request.method =="GET":
    if request.user.is_authenticated:
      cked_items = Checkout.objects.filter(userid=request.user.id)
      bl = []
      for items in cked_items:
        bl.append(items.bookid)
      books_serialized = BookSerializer(bl, many=True)   
      print(books_serialized)
      return render(request, 'accounts/profile_tbl.html', {'latest_book_list':books_serialized})

  if request.method =="POST":
    if request.user.is_authenticated:
      id_list = request.POST.getlist('boxes')
      print('id_list', id_list)
      if len(id_list) >  0:
        all_cked_items = Checkout.objects.filter(userid=request.user.id)
        cmn_items =[item for id in id_list for item in all_cked_items if item.bookid.id == int(id)]
        print('cmn_items',cmn_items)
        for item  in cmn_items:
          record = Checkout.objects.get(id=item.id)
          print('record', record)
          record.delete()
        for bid in id_list:
          book_record = Book.objects.get(id=int(bid))
          if not book_record.available:
            book_record.available=True
            book_record.save()
      cked_items_updated = Checkout.objects.filter(userid=request.user.id)    
      bl = []
      for items in cked_items_updated:
         bl.append(items.bookid)
      books_serialized = BookSerializer(bl, many=True)   
      print(books_serialized)
      return render(request, 'accounts/profile_tbl.html', {'latest_book_list':books_serialized})
  return HttpResponse("User is not logged in to show profile")

def user_login(request):
  if request.method == "POST":
    form = AuthenticationForm(request, data=request.POST)
    if form.is_valid():
      username = form.cleaned_data.get('username')
      password = form.cleaned_data.get('password')
      user = authenticate(username=username, password=password)
      if user is not None:
        login(request, user)
        ##messages.info(request, f"You are now logged")
        return render(request, 'landing/index.html')
      else:
        messages.error(request, "Invalid username or password")
    else:
      messages.error(request, "Invalid username or password")
  form = AuthenticationForm() 
  context = {}
  return render(request, 'registration/login.html', context={"login_form":form})

def sign_up(request):
  context = {}
  form = CustomUserCreationForm(request.POST or None)
  if request.method == "POST":
    if form.is_valid():
      user = form.save()
      login(request, user)
    return render(request, 'landing/index.html')
  context['form'] = form
  return render(request, 'registration/sign_up.html', context)

def user_logout(request):
  logout(request)
  return render(request,'registration/logged_out.html')

landing/views.py
from django.shortcuts import render
from django.template import loader
from django.http import HttpResponse
# Create your views here.

def index(request):
  #  template = loader.get_template('landing/index.html')
  #print('templates ', templates)
  return render(request, 'landing/index.html')

library/views.py
from django.shortcuts import render
from .models import Book
from rest_framework import generics
from .serializers import BookSerializer

from django.http import HttpResponse
from django.http.response import JsonResponse
from rest_framework.parsers import JSONParser
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response
from django.views import generic
from django.template import loader
from .models import Book
# Create your views here.
import datetime
import json

def index(request):
  latest_book_list = Book.objects.all()
  print('lates_book_list:', latest_book_list)
  template = loader.get_template('library/index.html')
  print('template ', template)
  context = {
      'latest_book_list': latest_book_list,
      }
  return HttpResponse(template.render(context, request))

#def books(request):
 # return HttpResponse("This is a book page.")


###just do get books for now
@api_view(['GET'])
def books(request):
  print('request', request)
  if request.method=='GET':
    books = Book.objects.all()
    books_serialized = BookSerializer(books, many=True)
    context = {
        'latest_book_list': books_serialized,
        }
    print('context ', context)
    return render(request, 'library/books.html',context)

class BookView(generic.ListView):
  template_name = 'library/booklist.html'
  context_object_name = 'all_book_list'

accounts/templates/accounts/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

accounts/templates/accounts/home.html
<!-- templates/home.html -->

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
  <p><a href="{% url 'logout' %}">Log Out</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a> |
  <a href="{% url 'signup' %}">Sign Up</a>
{% endif %}
{% endblock %}

accounts/templates/accounts/index.html
{% extends 'accounts/main.html' %}
{% block content %}
  <br>
	 <div class="container">
		 <h5> Welcome </h5>
	 </div>


{% endblock content %}

landing/templates/landing/index.html
{% extends 'landing/main.html' %}
{% block content %}
  <br>
	 <div class="container">
		 {% if user.is_authenticated%}
		 <h5> Welcome {{user.username}} </h5>
		 {%else %}
		 <h5> Welcome to the library. Please login to checkout books </h5>

		 {% endif %}

	 </div>


{% endblock content %}

landing/templates/landing/main.html
<!DOCTYPE html>
<html>
	<head>
		<title> LIBRARY</title>
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	</head>
	<body>
	        {% include 'landing/navbar.html' %}	
		<hr>
		{% block content %}

		{% endblock %}
		<hr>
		<div class="container">

		</div>
	</body>
</html>

landing/templates/landing/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home</span></a>
      </li>
      <li class="nav-item">
	      <a class="nav-link" href="{%url 'library:books' %}">Books</a>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item">
	      <a class="nav-link" href="{%url 'accounts:user_profile' %}">Profile</a>
      </li>
      <li class="nav-item">
	      <a class="nav-link" href="{%url 'accounts:user_logout' %}">Logout</a>
      </li>
      {%else %}
      <li class="nav-item">
	      <a class="nav-link" href="{%url 'accounts:user_login' %}">Login</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>

landing/templates/landing/new.html
<h1> This is landing template test </h1>

library/templates/library/books.html
{% extends 'library/main.html' %}
{% block content %}
  <br>
	 <div class="container">
			 <p> Books </p>
			 <table class="table table-hover">
				 <thead>
				 <tr>
					 <th scope="col">#</th>
					 <th scope="col">Name</th>
					 <th scope="col">Author</th>
					 <th scope="col">Available </th>
				 </tr>
				 </thead>
				 {% with book_list=latest_book_list.data %}
				   {%for item in  book_list %}
				   <tbody>
				    <tr>
					    <th scope="row">{{forloop.counter}}</th>
					    <td>{{item.name}}</td>
					    <td>{{item.author}}</td>
					    <td>{{item.available}}</td>
				    </tr>
				   </tbody>
				   {% endfor %}
				 {% endwith %}
			 </table>

	 </div>


{% endblock content %}

library/templates/library/index.html
{% extends 'library/main.html' %}
{% block content %}
  <br>
	 <div class="container">
		 <h5> Welcome </h5>
	 </div>


{% endblock content %}

library/templates/library/main.html
<!DOCTYPE html>
<html>
	<head>
		<title> LIBRARY</title>
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	</head>
	<body>
	        {% include 'library/navbar.html' %}	
		<hr>
		{% block content %}

		{% endblock %}
		<hr>
		<div class="container">

		</div>
	</body>
</html>

library/templates/library/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
	      <a class="nav-link" href="{%url 'landing:index' %}">Home</span></a>
      </li>
      <li class="nav-item">
	      <a class="nav-link" href="{%url 'accounts:user_profile' %}">Profile</a>
      </li>
      <li class="nav-item">
	      <a class="nav-link" href="{%url 'checkout:checkout_table' %}">Checkout</a>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item">
                <a class="nav-link" href="{%url 'accounts:user_logout' %}">Logout</a>
        </li>
	{% endif %}
    </ul>
  </div>
</nav>

library/templates/library/table.html
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">First</th>
      <th scope="col">Last</th>
      <th scope="col">Handle</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Mark</td>
      <td>Otto</td>
      <td>@mdo</td>
    </tr>
    <tr>
      <th scope="row">2</th>
      <td>Jacob</td>
      <td>Thornton</td>
      <td>@fat</td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td>Larry</td>
      <td>the Bird</td>
      <td>@twitter</td>
    </tr>
  </tbody>
</table>